### ISSUE TITLE
[Feature Request] MSVC support for the main header

### ISSUE THREAD

**Issue by Naios** [potswa/cxx_function#10]
As of revision e7beb8bfeb7172bef the `cxx_function.hpp` header doesn't support MSVC:

```
cxx_function/cxx_function.hpp(181): error C2065: 'has_trivial_copy_constructor': undeclared identifier (compiling source file test-continuable-connection-all.cpp)
cxx_function/cxx_function.hpp(182): note: see reference to class template instantiation 'cxx_function::impl::erasure_trivially_movable<erasure>' being compiled (compiling source file test-continuable-connection-all.cpp)
```

It would be nice if the generic header would also support MSVC (14+), so it could be used as drop-in replacement on all platforms.

**Comment by potswa** [comment]
MSVC tends to lag behind other compilers.

Attempting a port just now, it complains that the address of a (non-dynamic) `typeid` expression isn't a constant expression. So, I tried making the vtables non-constexpr on MSVC, and encountered a [clang bug](https://bugs.llvm.org//show_bug.cgi?id=32336).

Depending how many preprocessor macros and how much behavioral difference is required for MSVC support, it might only be checked-in on a branch.

Since it's infeasible install MSVC on my Mac and integrate it into the regular testing, it won't be supported consistently on the master branch in any case.

**Comment by Naios** [comment]
Thanks for taking care about this request so fast :-)

The CI https://www.appveyor.com/ supports continuous MSVC builds,
if you don't want to install a locale copy for testing repeatedly.

I know that it's mostly a pain to get it work on all major compilers,
however nowadays, MSVC isn't far behind Clang or GCC anymore so it should be feasible to support it.

**Comment by potswa** [comment]
I tried Appveyor but got stuck at trying to invoke the compiler. It says, `The term 'CL' is not recognized`…

Would you take a shot if I add you to the project?

**Comment by Naios** [comment]
Probably it's caused because there is no present MSVC project solution.

It's easier to create one if there is a present CMake file, so the CI can invoke the unit tests too.
You may take the CMake file from https://github.com/Naios/continuable/blob/master/CMakeLists.txt

When using CMake the build configuration should look like the following:

- - -
![ap0](https://cloud.githubusercontent.com/assets/1146834/24073400/88bdd34a-0bf7-11e7-8140-99f4910b6249.png)

- - -
![ap1](https://cloud.githubusercontent.com/assets/1146834/24073407/93ebdc4e-0bf7-11e7-85a6-836415e761a2.png)

- - -
![screenshot_7](https://cloud.githubusercontent.com/assets/1146834/24073418/b9374f9c-0bf7-11e7-98f4-e0a0b8f6553d.png)

**Comment by potswa** [comment]
The problem was that I was using Powershell (`.ps`) instead of cmd.exe (`.cmd`), so the `vcvarsall.bat` script wasn't exporting its environment variables.

It still ICEs on a couple tests, fails a couple others but outside the header, and I defeated another test where MSVC calls a move constructor where it should do elision.

Is this satisfactory for now? Thanks for pointing me at this website! Maybe I'll try to use its MinGW installation to test on old GCC versions.

**Comment by Naios** [comment]
This should work, thanks a lot for your efforts.

**Comment by Naios** [comment]
I know, I actually should open another issue for this:

My unit-tests show some issues related to the library reported by Clang and GCC  https://travis-ci.org/Naios/continuable/jobs/212572137#L604 .
The MSVC build did pass although there were a lot of warnings.

The [tests are passing](https://travis-ci.org/Naios/continuable/builds/212574768) when using `std::function` or `fu2::function` as backend for type-erasure.
My intention was to test my library with other functional type-erasure wrappers so I can verify my library as well as the used wrappers.

I uncommented `cxx_function` [in the tests for now](https://github.com/Naios/continuable/blob/master/test/unit-test/test-continuable.hpp#L208) but I'm looking forward to support it in the future.

For instance:
```
/home/travis/build/Naios/continuable/dep/cxx_function/cxx_function/cxx_function.hpp:436:8: error: 
      ambiguous partial specializations of
      'is_always_equal<std::allocator<(lambda at
      /home/travis/build/Naios/continuable/include/continuable/continuable-base.hpp:920:75)>,
      void, void>'
    && is_always_equal< allocator >::value > {};
       ^
```

**Comment by potswa** [comment]
Cool, thanks for supporting my project. Try the latest revision… It looks like your issues were fundamental issues with C++17 support. I'll dig deeper into Appveyor; if I can set up multiple targets, maybe it can help.

**Comment by Naios** [comment]
Thanks for fixing that so fast 👍 I highly appreciate that.

The [Travis build testing GCC and Clang](https://travis-ci.org/Naios/continuable/builds/212725218) seems ok now.
The [AppVeyor MSVC 2015 build](https://ci.appveyor.com/project/Naios/continuable/build/%2352) reports 2 warning types on `\w4` (the build passes too):

**1**
```
c:\projects\continuable\dep\cxx_function\cxx_function\cxx_function.hpp(625): warning C4706: assignment within conditional expression [C:\projects\continuable\test\unit-test\test-continuable-4.vcxproj]
```

**2**
```
C:\projects\continuable\dep\cxx_function\cxx_function/cxx_function.hpp(1180): warning C4522: 'cxx_function::function<void (cxx_function::function<void (void)>)>': multiple assignment operators specified (compiling source file C:\projects\continuable\test\unit-test\test-continuable-connection-any.cpp) [C:\projects\continuable\test\unit-test\test-continuable-4.vcxproj]
  C:\projects\continuable\include\continuable/continuable-base.hpp(1481): note: see reference to class template instantiation 'cxx_function::function<void (cxx_function::function<void (void)>)>' being compiled (compiling source file C:\projects\continuable\test\unit-test\test-continuable-connection-any.cpp)
  c:\projects\continuable\test\unit-test\test-continuable.hpp(111): note: see reference to class template instantiation 'cti::abi_v1::continuable_base<cxx_function::function<void (cxx_function::function<void (void)>)>,cti::abi_v1::detail::util::identity<>>' being compiled (compiling source file C:\projects\continuable\test\unit-test\test-continuable-connection-any.cpp)
  C:\projects\continuable\test\unit-test\test-continuable-connection-any.cpp(29): note: see reference to function template instantiation 'auto continuation_provider<Provider>::supply<>(void)' being compiled
```

**Comment by potswa** [comment]
The AppVeyor build still has a simplistic script — it doesn't report failures :P . I'll try and fix that. Will also take a look at the warnings tomorrow.

**Comment by potswa** [comment]
MSVC has been working for the last couple years except for the scoped_allocator testcase, so I'm closing this. Please open a new bug with any specific MSVC request.
