### ISSUE TITLE
Clang compilation error.

### ISSUE THREAD

**Issue by LEW21** [potswa/cxx_function#7]
Compiling the cxx_function.hpp with clang++ 3.7.0 and gcc 5.2.0's libstdc++ produces an error:

```
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/bits/uses_allocator.h:49:31: error: 'allocator_type' is a protected member of 'cxx_function::impl::wrapper_no_allocator'
                                   __void_t<typename _Tp::allocator_type>>
```

Making this typedef public fixes the error, and makes cxx_function usable with clang.

**Comment by potswa** [comment]
Strangely, Clang is not applying SFINAE to the previous line of libstdc++. `__void_t<typename _Tp::allocator_type>` should get the same access error and cancel the `__uses_allocator_helper` specialization. Looks like a Clang bug.

I fixed the issue by renaming the internal member. Thanks for the report! I've added a clang+libstdc++ configuration to my testsuite script, and all the cases are passing now.
