### ISSUE TITLE
VS2015 support

### ISSUE THREAD

**Issue by Klaim** [potswa/cxx_function#8]
I tried to compile this header with VS2015U1 and got trouble. I didn't make a patch because I think my fixes might be just hacks and I'm not sure which issues are compiler issues and which one are from the code.

I wrote this "test" and tried to compile it alone in VS2015U1:

```
#include <utilcxx/function.hpp>

void foo()
{
    cxx_function::function<void()> f;
    cxx_function::unique_function<void()> u;

}
```

Here function.hpp is a copy past of current master of cxx_function.
## First issue:

I think this is a compiler issue but I'm not totally sure yet. 

```
utilcxx\function.hpp(360): error C2039: 'value': is not a member of '`global namespace''
```

line 360:

```
template< typename t, typename v >
    struct is_always_equal< t, v, typename std::enable_if< decltype (std::declval< t >() == std::declval< t >())::value >::type >
        : std::true_type {};
```

It seems like VS is failing to understand the `decltype()` usage in the enable_if, and I think previous versions were having issues too. Anyway I replaced the code by this to try to go forward, it removes this error:

```
template< typename t, typename v >
    using sometype = decltype (std::declval< t >() == std::declval< t >());

    template< typename t, typename v >
    struct is_always_equal< t, v, typename std::enable_if< sometype<t,v>::value >::type >
        : std::true_type {};
```
## Second issue:

The second error is more tricky and general: 

```
utilcxx\function.hpp(795): error C2039: 'wrapper_base<void __cdecl(void)>': is not a member of 'cxx_function::impl::wrapper<cxx_function::impl::is_copyable_all_callable<cxx_function::function<void (void)>,void (void)>::temp,cxx_function::impl::wrapper_no_allocator,void (void)>'
utilcxx\function.hpp(1075): note: see reference to class template instantiation 'cxx_function::impl::wrapper<cxx_function::impl::is_copyable_all_callable<cxx_function::function<void (void)>,void (void)>::temp,cxx_function::impl::wrapper_no_allocator,void (void)>' being compiled
main.cpp(5): note: see reference to class template instantiation 'cxx_function::function<void (void)>' being compiled
```

Here the issue seems to be that you are re-using the current type name as part of the name of a base class when doing using declarations to import base type's members into the child type.
For example:

```
template< template< typename ... > class is_targetable, typename allocator_manager, typename ... sig >
    class wrapper
        : public allocator_manager
        , wrapper_base< sig ... > {
        //...
        using wrapper::wrapper_base::storage;
        using wrapper::wrapper_base::storage_address;
        using wrapper::wrapper_base::init;
```

Here, my understanding of the C++ standard (I might be wrong) is that repeating `wrapper` in the using declarations are unnecessary if not an error.
Anyway, removing them everywhere the compiler point the same issue seems to make things go forward. 

```
template< template< typename ... > class is_targetable, typename allocator_manager, typename ... sig >
    class wrapper
        : public allocator_manager
        , wrapper_base< sig ... > {
        //...
        using wrapper_base::storage;                   // ok
        using wrapper_base::storage_address;    // ok
        using wrapper_base::init;                          // ok
```

I'm even less sure for this case who is correct, the compiler or the code...
## Third issue:

Not sure again what is correct.

```
utilcxx\function.hpp(908): error C2876: 'cxx_function::impl::wrapper_dispatch<cxx_function::impl::wrapper_base<void (void)>,0,void (void)>': not all overloads are accessible
```

This is modified code in the `wrapper` class definition:

```
public:
        using wrapper_base::operator ();  // error
        using wrapper_base::target;
        using wrapper_base::target_type;
        using wrapper_base::verify_type;
        using wrapper_base::operator bool;
        using wrapper_base::complete_object_address;
```

I figured that `operator()` is actually defined in `wrapper_forward` class, from which `wrapper_base` inherit from publicly. So at first glance it seems that the compiler is wrong as the operator should be accessible. That being said, this case is a bit tricky because I'm not sure if it's correct to have using declaration make reference to a name which is defined in a parent class 2 levels up.
Anyway, the cleanest way to fix this is to just do a using declaration in `wrapper_base` to make sure the compiler see the function all the way down.

```
    template< typename ... sig >
    class wrapper_base
        : public wrapper_dispatch< wrapper_base< sig ... >, 0, sig ... > {
        template< template< typename ... > class, typename, typename ... >
        friend class wrapper;
        typedef std::aligned_storage< sizeof(void *[3]) >::type effective_storage_type;
    protected:
        using wrapper_dispatch::operator();  // line added, fixes the error
```

The next errors were the same as the second one but for the `function` class, which led to this code:

```
    template< typename ... sig >
class function
    : impl::wrapper< impl::is_copyable_all_callable< function< sig ... >, sig ... >::template temp, impl::wrapper_no_allocator, sig ... > {
    template< template< typename ... > class, typename, typename ... >
    friend class impl::wrapper;
public:
    using wrapper::wrapper;

    function() noexcept = default; // Investigate why these are needed. Compiler bug?
    function(function && s) noexcept = default;
    function(function const &) = default;
    function & operator = (function && s) noexcept = default;
    function & operator = (function const & o) = default;

    using wrapper::operator ();
    using wrapper::operator =;
    using wrapper::swap;
    using wrapper::target;
    using wrapper::target_type;
    using wrapper::verify_type;
    using wrapper::operator bool;
    using wrapper::complete_object_address;

    using wrapper::assign;
    using wrapper::emplace_assign;
    using wrapper::allocate_assign;
    // No allocator_type or get_allocator.
};
```
## Fourth Issue: 

With this change I got the following error:

```
utilcxx\function.hpp(1102): error C2535: 'cxx_function::function<void (void)>::function(source &&)': member function already defined or declared
utilcxx\function.hpp(1081): note: compiler has generated 'cxx_function::function<void (void)>::function' here
main.cpp(5): note: see reference to class template instantiation 'cxx_function::function<void (void)>' being compiled
```

So the constructor delegation on line `using wrapper::wrapper;` is (obviously) importing constructors from `wrapper`, which is good, but the compiler don't like that we redefine some of the constructors. So I removed the unnecessary constructor to get this:

```
    template< typename ... sig >
class function
    : impl::wrapper< impl::is_copyable_all_callable< function< sig ... >, sig ... >::template temp, impl::wrapper_no_allocator, sig ... > {
    template< template< typename ... > class, typename, typename ... >
    friend class impl::wrapper;
public:
    using wrapper::wrapper;   // apparent source of the problem?
    // constructors removed HERE
    // ...
};
```

With this modification I still get the same error, with the same source, that is the using constructor declaration.
Replacing this line by this one seems to work but I suspect that it's actually wrong if not misleading:

```
    template< typename ... sig >
class function
    : impl::wrapper< impl::is_copyable_all_callable< function< sig ... >, sig ... >::template temp, impl::wrapper_no_allocator, sig ... > {
    template< template< typename ... > class, typename, typename ... >
    friend class impl::wrapper;
public:
    // constructor forwarding everything to the base type
    template< class... anything >
    function( anything&&... x ) : wrapper( std::forward<anything>(x) ) {}
```

This is dirty and I'm sure it have bloody edge cases.

For `unique_function` I did the same, with a twist: I kept the deleted operations so that it does what we expect. I ended up with this:

```
template< typename ... sig >
class unique_function
    : impl::wrapper< impl::is_all_callable< sig ... >::template temp, impl::wrapper_no_allocator, sig ... > {
    template< template< typename ... > class, typename, typename ... >
    friend class impl::wrapper;
public:
    template< class... anything >
    unique_function(anything&&... x) : wrapper( std::forward<anything>(x)... ) {}

    unique_function(unique_function const &) = delete;
    unique_function & operator = (unique_function const & o) = delete;

    using wrapper::operator ();
    using wrapper::operator =;
    using wrapper::swap;
    using wrapper::target;
    using wrapper::target_type;
    using wrapper::verify_type;
    using wrapper::operator bool;
    using wrapper::complete_object_address;

    using wrapper::assign;
    using wrapper::emplace_assign;
    using wrapper::allocate_assign;
    // No allocator_type or get_allocator.
};
```

At this point I changed my test to this executable program:

```
#include <iostream>
#include <utilcxx/function.hpp>

int main()
{
    cxx_function::function<void()> f = [] { std::cout << "Hello, " << std::endl; };
    cxx_function::unique_function<void()> u = [] { std::cout << "World!" << std::endl; };

    f();
    u();
}
```

This compiles and run correctly for me.

I tried some tests but they fail, for example swap.cpp fails with an error suggesting that the template forwarding constructor was indeed too dirty.

Anyway I don't have enough time to go further for now, tell me if I can help in some ways.

**Comment by Klaim** [comment]
I managed to reproduce issue 4 which I believe is a compiler bug as expected: https://connect.microsoft.com/VisualStudio/feedback/details/2184007

**Comment by potswa** [comment]
Thanks for your detailed report! Currently there's no MSVC support, as I don't really run Windows.

I'll see if I can integrate your patches and get some testcases working on webcompiler.cloudapp.net, which hosts a free VS2015. But, it's offline right now.

Indeed the last issue is the hairiest. Inheriting constructors weren't really designed to work with SFINAE and the compiler needs to be massaged to make the features work together. Forwarding is probably the best workaround; it doesn't achieve quite the same results (especially given initializer list arguments) but with some SFINAE in the final derived classes it should be good enough, e.g.

```
template< class... anything,
    typename std::enable_if_t< std::is_constructible< wrapper, anything ... >::value >
                               * = nullptr >
unique_function(anything&&... x) : wrapper( std::forward<anything>(x)... ) {}
```

**Comment by Klaim** [comment]
> I'll see if I can integrate your patches and get some testcases working on webcompiler.cloudapp.net, which hosts a free VS2015. But, it's offline right now.

Yeah I tried so that I could show the issues, but the compilation hit timeout, so it's not useable for this case. I think there is a visual studio online service somewhere but I don't know if it's free.

After I used forwarding with issue 4 I tried running the swap test which failed on runtime. I didn't try to go further so I don't know yet what was the issue.

**Comment by potswa** [comment]
I've pushed a [branch](https://github.com/potswa/cxx_function/tree/msvc_port) with preliminary support. Simpler testcases seem to pass but containers seem to be broken. I suspect that the online compilers had been running into memory quotas. Now rextester.com seems to work, but the official MS one at cloudapp.net still drops the connection sometimes.

**Comment by Klaim** [comment]
I'll try to test it in my code as before on my vs2015u1 setup, but I can't promise when I'll be able to do so.

**Comment by potswa** [comment]
I've updated the branch. Now the testcases pass, modulo `std::result_of` SFINAE and features depending on it. A few testcases are different from the trunk, if you want to independently test. I'm closing this; please report any further difficulties in a new bug.
